{
 "title": "🐴 Firehose Drift",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(head_block_time_drift, network)"
    }
   },
   {
    "name": "block_version",
    "label": "Block Version",
    "query": {
     "query": "label_values(head_block_time_drift{network=~\"$network\"}, block_version)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(head_block_time_drift{network=~\"$network\", block_version=~\"$block_version\"}, app)"
    }
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(head_block_time_drift{network=~\"$network\", block_version=~\"$block_version\", app=~\"$app\"}, hostname)"
    }
   },
   { "name": "query0", "query": { "query": "" } },
   { "name": "DS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Chain Flow ( For Alerts )",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(head_block_number{instance=\"$instance\",job=\"$job\"}[60m]) / 10",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "firehose_requests_counter | firehose_active_requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "firehose_requests_counter{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "firehose_active_requests{instance=\"the_graph_mip\",job=\"firehose-eth-metrics\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "grpc_server_handled_total",
   "type": "timeseries",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "grpc_server_handled_total{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{label_name}} {{ grpc_method }} {{ grpc_service }}"
    }
   ]
  },
  {
   "title": "Letency gRPC ",
   "type": "heatmap",
   "description": "Histogram of response latency (seconds) of gRPC that had been application-level handled by the server",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handling_seconds_bucket{instance=\"$instance\",job=\"$job\"}[$__range])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ready{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "grpc_server_msg_received_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 20 },
   "targets": [
    {
     "expr": "grpc_server_msg_received_total{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{  grpc_method }} - {{ grpc_service }} - {{ grpc_type }}"
    }
   ]
  },
  {
   "title": "head block time drift",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "head_block_time_drift{instance=\"the_graph_mip\",job=\"firehose-eth-metrics\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "head block number",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "head_block_number{instance=\"$instance\",job=\"$job\"} > 0",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "head block increase rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase (head_block_number{instance=\"$instance\",job=\"$job\"}[1m]) / 60 ",
     "legendFormat": "{{ app }}"
    }
   ]
  }
 ]
}