{
 "title": "Indexing Performance Metrics",
 "tags": [ "ok" ],
 "time": { "from": "2023-05-30T21:28:58.000Z", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "DS", "label": "DATASOURCE", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Subgraphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Subgraphs Names ( the only check )",
   "type": "table",
   "description": "The only way to find subgraphs actual names",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "graph_prom_alloc_ages{instance=\"GM1\",job=\"exporter-graph-custom\"}",
     "legendFormat": "{{ name }} {{ id }}"
    }
   ]
  },
  {
   "title": "Blocks behind over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "abs(deployment_head{job=\"$job\", instance=\"$instance\"} - on (network) group_left ethereum_chain_head_number{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "Operator Balance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Operator ETH Balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indexer_agent_operator_eth_balance{instance=\"GM1\",job=\"graph_agent\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator ETH Balance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 18 },
   "targets": [
    {
     "expr": "indexer_agent_operator_eth_balance{instance=\"GM1\",job=\"graph_agent\"}",
     "legendFormat": "ETH:"
    }
   ]
  },
  { "title": "MAIN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Fall behing [ 2 ] < 250",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "abs(deployment_head{job=\"$job\", instance=\"$instance\"} - on (network) group_left ethereum_chain_head_number{job=\"$job\", instance=\"$instance\"}) > 2 < 250",
     "legendFormat": "{{ network }}"
    }
   ]
  },
  {
   "title": "All subgraphs sync rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(deriv(deployment_head{job=\"$job\", instance=\"$instance\"}[10m]) * 60)",
     "legendFormat": "Total Sync Rate"
    }
   ]
  },
  {
   "title": "Individual subgraph sync rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "deriv(deployment_head{job=\"$job\", instance=\"$instance\"}[10m]) * 60",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Gnosis RPC",
   "type": "bargauge",
   "description": "Whether the provider has failed \n[ 0 = ok ]\n[ 1 = net_version failed ]\n[ 2 = get genesis failed ]\n[ 3 = net_version timeout ]\n[ 4 = get genesis timeout ]",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_rpc_status{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ provider }}"
    }
   ]
  },
  {
   "title": "store connection error",
   "type": "stat",
   "description": "The number of Postgres connections errors",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "store_connection_error_coun{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Deployment Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_count{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "notification queue usage",
   "type": "stat",
   "description": "Time series of pg_notification_queue_usage()",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notification_queue_usage{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "query semaphore wait ms",
   "type": "stat",
   "description": "Moving average of time spent on waiting for postgres query semaphore",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_semaphore_wait_ms{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "store connection checkout",
   "type": "stat",
   "description": "The number of Postgres connections currently checked out",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "store_connection_checkout_count{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "registered_metrics",
   "type": "stat",
   "description": "Tracks the number of registered metrics on the node",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "registered_metrics{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "query effort ms",
   "type": "stat",
   "description": "Moving average of time spent running queries",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_effort_ms{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "query_kill_rate",
   "type": "stat",
   "description": "The rate at which the load manager kills queries",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_kill_rate{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "store connection pool size",
   "type": "stat",
   "description": "Overall size of the connection pool",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "store_connection_pool_size_count{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "store connection wait time ms",
   "type": "stat",
   "description": "Average connection wait time",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "store_connection_wait_time_ms{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "metrics errors",
   "type": "stat",
   "description": "Counts Prometheus metrics register errors",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(metrics_register_errors{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "rate(metrics_unregister_errors{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Optimism :-( chain head number",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"optimism\"}",
     "legendFormat": "Gnosis chain progress"
    }
   ]
  },
  {
   "title": "OPTIMISM :-( CHAIN HEAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"optimism\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Optimism chain head Increase for alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"optimism\"}[120s]) / 10",
     "legendFormat": "{{ network }}"
    }
   ]
  },
  {
   "title": "gnosis notification_queue_recvd",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(notification_queue_recvd{channel=\"chain_head_updates\",instance=\"$instance\",job=\"$job\",network=\"optimism\"}[$__rate_interval])",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "rate(notification_queue_recvd{channel=\"store_events\",instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  { "title": "GNOSIS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Gnosis chain head number",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"gnosis\"}",
     "legendFormat": "Gnosis chain progress"
    }
   ]
  },
  {
   "title": "GNOSIS CHAIN HEAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"gnosis\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Gnosis chain head Increase for alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"gnosis\"}[120s]) / 10",
     "legendFormat": "{{ network }}"
    }
   ]
  },
  {
   "title": "gnosis notification_queue_recvd",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "rate(notification_queue_recvd{channel=\"chain_head_updates\",instance=\"$instance\",job=\"$job\",network=\"gnosis\"}[$__rate_interval])",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "rate(notification_queue_recvd{channel=\"store_events\",instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  { "title": "ETHERIUM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Etherium MainNet",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"mainnet\"}",
     "legendFormat": "Gnosis chain progress"
    }
   ]
  },
  {
   "title": "ETHERIUM CHAIN HEAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"mainnet\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Etherium chain head Increase for alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"mainnet\"}[120s]) / 10",
     "legendFormat": "{{ network }}"
    }
   ]
  },
  {
   "title": "Etherium notification_queue_recvd",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "rate(notification_queue_recvd{channel=\"chain_head_updates\",instance=\"$instance\",job=\"$job\",network=\"mainnet\"}[$__rate_interval])",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "rate(notification_queue_recvd{channel=\"store_events\",instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  { "title": "ARBITRUM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "ARBITRUM MainNet",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"arbitrum-one\"}",
     "legendFormat": "Gnosis chain progress"
    }
   ]
  },
  {
   "title": "ARBITRUM CHAIN HEAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"arbitrum-one\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "ARBITRUM chain head Increase for alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"arbitrum-one\"}[30s]) / 100",
     "legendFormat": "{{ network }}"
    }
   ]
  },
  { "title": "CELO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Celo MainNet",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"celo\"}",
     "legendFormat": "Colo chain progress"
    }
   ]
  },
  {
   "title": "CELO CHAIN HEAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"celo\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Celo chain head Increase for alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"celo\"}[120s]) / 10",
     "legendFormat": "{{ network }}"
    }
   ]
  },
  { "title": "Avalanche", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Avalanche MainNet",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"avalanche\"}",
     "legendFormat": "Gnosis chain progress"
    }
   ]
  },
  {
   "title": "Avalanche CHAIN HEAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"avalanche\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Avalanche chain head Increase for alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{instance=\"$instance\",job=\"$job\",network=\"avalanche\"}[120s]) / 10",
     "legendFormat": "{{ network }}"
    }
   ]
  },
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "query_cache_status_count",
     "type": "timeseries",
     "description": "Count toplevel GraphQL fields executed and their cache status",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "rate(query_cache_status_count{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ cache_status }}"
      }
     ]
    },
    {
     "title": "query_result_max",
     "type": "timeseries",
     "description": "the maximum size of a query result (in CacheWeight)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "targets": [
      {
       "expr": "query_result_max{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{ __name__ }}"
      }
     ]
    },
    {
     "title": "Eth RPC Errors per minute (all subgraphs) [ 1h ]",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(eth_rpc_errors{job=\"$job\", instance=\"$instance\"}[24h])) / 24"
      }
     ]
    },
    {
     "title": "Eth RPC Request Duration per Subgraph",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time(deployment_eth_rpc_request_duration{job=\"$job\", instance=\"$instance\",method=\"eth_getLogs\",provider=\"no-archive\"}[15m])",
       "legendFormat": "{{deployment}}"
      }
     ]
    }
   ]
  }
 ]
}