{
 "title": "Autoagora",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "SYSTEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "process_virtual_memory_bytes",
   "type": "timeseries",
   "description": "process_virtual_memory_bytes",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"autoagora\"}",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "process_resident_memory_bytes",
   "type": "timeseries",
   "description": "process_resident_memory_bytes",
   "gridPos": { "h": 9, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"autoagora\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Open FDS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"autoagora\"}",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"GM1\",job=\"node_exporter\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"GM1\",job=\"node_exporter\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Running Containers ( alerts )",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"GM1\",job=\"node_exporter\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"GM1\",job=\"node_exporter\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"GM1\",job=\"node_exporter\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"GM1\",job=\"node_exporter\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"GM1\",job=\"node_exporter\"} - node_memory_MemFree_bytes{instance=\"GM1\",job=\"node_exporter\"} - (node_memory_Cached_bytes{instance=\"GM1\",job=\"node_exporter\"} + node_memory_Buffers_bytes{instance=\"GM1\",job=\"node_exporter\"} + node_memory_SReclaimable_bytes{instance=\"GM1\",job=\"node_exporter\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"GM1\",job=\"node_exporter\"} + node_memory_Buffers_bytes{instance=\"GM1\",job=\"node_exporter\"} + node_memory_SReclaimable_bytes{instance=\"GM1\",job=\"node_exporter\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"GM1\",job=\"node_exporter\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"GM1\",job=\"node_exporter\"} - node_memory_SwapFree_bytes{instance=\"GM1\",job=\"node_exporter\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "gauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"GM1\",job=\"node_exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"GM1\",job=\"node_exporter\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"GM1\",job=\"node_exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"GM1\",job=\"node_exporter\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "QUERIES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Fees Total",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Fees_total{job=\"processor-autoagora\"} * 10^-18",
     "legendFormat": "{{ subgraph }}"
    }
   ]
  },
  {
   "title": "Operator ETH Balance",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indexer_agent_operator_eth_balance{instance=\"GM1\",job=\"graph_agent\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(indexer_service_queries_failed{job=\"indexer_service\", instance=\"GM1\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(indexer_service_queries_ok{job=\"indexer_service\", instance=\"GM1\"})",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Operator ETH Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 20 },
   "targets": [
    {
     "expr": "indexer_agent_operator_eth_balance{instance=\"GM1\",job=\"graph_agent\"}",
     "legendFormat": "{{ ETH }}"
    }
   ]
  },
  {
   "title": "DEAD SUBGRAPHS in [ $__range ]",
   "type": "table",
   "description": "LEADERBOARD PER RANGE",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sort_desc(sum by(deployment) (increase(indexer_service_queries_total{job=\"indexer_service\", instance=\"GM1\"}[$__range])))  < 100",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Total queries per [ $__range ]",
   "type": "barchart",
   "description": "LEADERBOARD PER RANGE",
   "gridPos": { "h": 15, "w": 15, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(sum by(deployment) (increase(indexer_service_queries_total{job=\"indexer_service\", instance=\"GM1\"}[$__range]))) > 0",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Total queries per deployment since last restart ( log )",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(sum by(deployment) (indexer_service_queries_total{job=\"indexer_service\", instance=\"GM1\"}))",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  { "title": "Bandit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Fees Total",
   "type": "timeseries",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Fees_total{job=\"processor-autoagora\"} * 10^-18",
     "legendFormat": "{{ subgraph }}"
    }
   ]
  },
  {
   "title": "Queries Failed vs OK per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_failed[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_service_queries_ok[1m]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Average Queries per Second for the interval",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_ok{job=\"indexer_service\", instance=\"GM1\"}[$__interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(indexer_service_queries_failed{job=\"indexer_service\", instance=\"GM1\"}[$__interval]))",
     "legendFormat": "FAIL"
    }
   ]
  },
  {
   "title": "GRT / second over all subgraphs",
   "type": "timeseries",
   "description": "sum(rate(Fees_total{job=\"processor-autoagora\"}[10m])) * 10^-18",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(Fees_total{job=\"processor-autoagora\"}[10m])) * 10^-18",
     "legendFormat": "GRT per second ( all subgraphs )"
    }
   ]
  },
  {
   "title": "Queries by subgraph per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (deployment) (rate(indexer_service_queries_total{instance=\"GM1\",job=\"indexer_service\"}[1m]))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "GRT / second per subgraph",
   "type": "timeseries",
   "description": "rate(Fees_total{job=\"processor-autoagora\"}[60s]) * 10^-18",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(Fees_total{job=\"processor-autoagora\"}[60s]) * 10^-18",
     "legendFormat": "{{subgraph}}"
    }
   ]
  },
  {
   "title": "Bandit mean",
   "type": "timeseries",
   "gridPos": { "h": 32, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "bandit_mean{instance=\"GM1\",job=\"autoagora\"}",
     "legendFormat": "{{subgraph}}"
    }
   ]
  },
  {
   "title": "Bandit standard deviation",
   "type": "timeseries",
   "gridPos": { "h": 32, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bandit_stddev{instance=\"GM1\",job=\"autoagora\",alias=\"Autoagora\"}",
     "legendFormat": "{{subgraph}}"
    }
   ]
  },
  {
   "title": "Bandit sampled price multiplier",
   "type": "timeseries",
   "gridPos": { "h": 31, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "bandit_price_multiplier{instance=\"GM1\",job=\"autoagora\",alias=\"Autoagora\"}",
     "legendFormat": "{{subgraph}}"
    }
   ]
  },
  {
   "title": "Bandit reward",
   "type": "timeseries",
   "gridPos": { "h": 31, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bandit_reward{instance=\"GM1\",job=\"autoagora\"}",
     "legendFormat": "{{subgraph}}"
    }
   ]
  }
 ]
}