{
 "title": "Query Performance Metrics",
 "tags": [ "indexer service" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Failed Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "indexer_service_queries_failed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Average Queries per Second in  [ $__range ]",
   "type": "timeseries",
   "description": "SHow how much queries total per chosen time frame",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_ok{job=\"$job\", instance=\"$instance\"}[$__range]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(indexer_service_queries_failed{job=\"$job\", instance=\"$instance\"}[$__range]))",
     "legendFormat": "FAIL"
    }
   ]
  },
  {
   "title": "Total queries per deployment in [ $__range ]",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 9, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (deployment) (increase(indexer_service_queries_total{job=\"$job\", instance=\"$instance\"}[$__range])))",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Total queries percentage per deployment in [ $__range ]",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (deployment) (increase(indexer_service_queries_total{job=\"$job\", instance=\"$instance\"}[$__range])))",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Queries Failed vs OK in [ $range ]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(indexer_service_queries_failed{job=\"$job\", instance=\"$instance\"}[$__range]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase(indexer_service_queries_ok{job=\"$job\", instance=\"$instance\"}[$__range]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Average Queries per Second in [ $__range ]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_ok{job=\"$job\", instance=\"$instance\"}[$__range]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(indexer_service_queries_failed{job=\"$job\", instance=\"$instance\"}[$__range]))",
     "legendFormat": "FAIL"
    }
   ]
  },
  {
   "title": "Queries Failed vs OK in [ $__range ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(indexer_service_queries_failed{job=\"$job\", instance=\"$instance\"}[$__range]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase(indexer_service_queries_ok{job=\"$job\", instance=\"$instance\"}[$__range]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Queries Failed vs OK per second",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_failed{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_service_queries_ok{job=\"$job\", instance=\"$instance\"}[100s])) / 10",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Total queries by subgraph per second",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (deployment) (rate(indexer_service_queries_total{job=\"indexer_service\"}[5m]))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Erors per $__range",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(indexer_error[$__range])",
     "legendFormat": "{{code}}  /  {{job}}"
    }
   ]
  },
  {
   "title": "Indexer errors (over 5 minutes, by code)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(indexer_error[30s])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Channel Messages Failed vs OK over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(indexer_service_channel_messages_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(indexer_service_channel_messages_ok)",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Total Channel Messages by Servicenode per second [stacked]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(indexer_service_channel_messages_total[100s]) / 10",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cost Model Queries over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(indexer_service_cost_model_queries_invalid)",
     "legendFormat": "queries_invalid"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries)",
     "legendFormat": "batch queries"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries_failed)",
     "legendFormat": "batch queries_failed"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries_invalid)",
     "legendFormat": "batch  queries_invalid"
    }
   ]
  },
  {
   "title": "Total Cost Model Batch Queries by Servicenode per second ( need to edit and remove * 10 )",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(indexer_service_cost_model_batch_queries{job=\"$job\", instance=\"$instance\"}[100s]) / 10",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Channel Messages Failed vs OK per second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_channel_messages_failed[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_service_channel_messages_ok[1m]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Cost Model Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_cost_model_queries_invalid{job=\"$job\", instance=\"$instance\"}[1m]))",
     "legendFormat": "queries_invalid"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries{job=\"$job\", instance=\"$instance\"}[1m]))",
     "legendFormat": "batch queries"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries_failed[1m]))",
     "legendFormat": "batch queries_failed"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries_invalid[1m]))",
     "legendFormat": "batch  queries_invalid"
    }
   ]
  }
 ]
}